image: ruby:2.7

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

pages:
  script:
    - rm .gitlab-ci.yml
    - rm -rf .git/
  artifacts:
    paths:
      - "*"
  rules:
    - if: '$CI_COMMIT_BRANCH == "deploy"'