name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    container:
      image: alpine:3.15
    steps:
      - uses: actions/checkout@v2

      - name: Install tiled
        run: apk add --update tiled --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/
      - name: Build tiles
        run: mkdir dist && tiled -platform offscreen --export-map json map.tmx dist/main.json

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
